#!/usr/bin/env python3
"""
AI SOC Assistant - Working Prototype (Demo Mode)
Shows what the assistant output looks like without needing API keys.
This demonstrates the full flow: triage -> tool calls -> summary -> report
"""

import json
from datetime import datetime


class SOCAssistantDemo:
    """Demo version of SOC Assistant with hardcoded logic (no API calls)."""
    
    def __init__(self):
        self.known_iocs = {
            "203.0.113.5": {"threat": "Emotet C2", "confidence": 99},
            "malware-beacon.com": {"threat": "Emotet C2", "confidence": 98},
            "d41d8cd98f00b204e9800998ecf8427e": {"threat": "Emotet trojan", "confidence": 96},
        }
        self.ip_scores = {
            "203.0.113.5": 85,
            "192.0.2.10": 45,
            "198.51.100.1": 10,
        }
    
    def triage_alert(self, alert_text: str) -> dict:
        """Demo triage (no real API calls, just hardcoded logic)."""
        
        # Simulate LLM analysis
        print(f"\n[LLM ANALYSIS]")
        print(f"Alert text: {alert_text}")
        print(f"  └─ Threat type: Detecting based on keywords...")
        
        severity = "CRITICAL" if "multiple failed" in alert_text.lower() else "HIGH"
        
        # Simulate tool calls
        print(f"\n[TOOL CALLS]")
        tool_results = []
        
        if "203.0.113.5" in alert_text:
            print(f"  1. check_ip_reputation('203.0.113.5')")
            print(f"     └─ Result: abuse_score=85, HIGH_RISK")
            tool_results.append(("IP", "203.0.113.5", 85, "HIGH RISK"))
            
            print(f"  2. search_known_iocs('203.0.113.5')")
            print(f"     └─ Found: Emotet C2 (confidence: 99%)")
            tool_results.append(("IOC", "203.0.113.5", "Emotet C2", 99))
        
        if "malware_payload.exe" in alert_text or "d41d8cd98f00b204e" in alert_text:
            print(f"  3. search_known_iocs('d41d8cd98f00b204e9800998ecf8427e')")
            print(f"     └─ Found: Emotet trojan (confidence: 96%)")
            tool_results.append(("IOC", "d41d8cd98f00b204e...", "Emotet trojan", 96))
        
        # Simulate LLM summary
        print(f"\n[LLM SUMMARY]")
        
        if "203.0.113.5" in alert_text and "failed" in alert_text.lower():
            summary = "Brute-force attack detected. Source IP 203.0.113.5 (high abuse score, known Emotet C2) attempted 45 failed logins against admin account. Attack succeeded. Attacker now has admin access and can move laterally."
            recommendation = "ISOLATE IMMEDIATELY. Force password reset. Scan for persistence."
        elif "malware_payload" in alert_text:
            summary = "Malware execution detected. File d41d8cd98... matches Emotet trojan (96% confidence). User likely clicked malicious email attachment."
            recommendation = "KILL PROCESS. Isolate machine. Scan for C2 beaconing."
        else:
            summary = "Unknown threat detected. Requires manual investigation."
            recommendation = "MONITOR and INVESTIGATE"
        
        print(f"  └─ {summary}")
        print(f"  └─ Recommendation: {recommendation}")
        
        return {
            "alert": alert_text,
            "severity": severity,
            "summary": summary,
            "recommendation": recommendation,
            "tool_results": tool_results,
            "timestamp": datetime.now().isoformat(),
        }
    
    def format_report(self, triage_result: dict) -> str:
        """Format as structured markdown report."""
        report = f"""
# Alert Triage Report

**Timestamp:** {triage_result['timestamp']}
**Severity:** {triage_result['severity']}

## Original Alert
{triage_result['alert']}

## Assessment
{triage_result['summary']}

## Recommendation
**{triage_result['recommendation']}**

## Tool Analysis Details
"""
        if triage_result['tool_results']:
            report += "\n| Type | Indicator | Score/Threat | Confidence |\n"
            report += "|------|-----------|--------------|------------|\n"
            for tool_result in triage_result['tool_results']:
                tool_type, indicator, value, conf = tool_result
                report += f"| {tool_type} | {indicator} | {value} | {conf} |\n"
        
        report += f"""
---
*Generated by AI SOC Assistant - Day 28 Prototype*
"""
        return report


def main():
    """Demo the assistant on 3 sample alerts."""
    assistant = SOCAssistantDemo()
    
    sample_alerts = [
        "Alert: Multiple failed logins for admin from IP 203.0.113.5. 45 attempts in 5 minutes. Then 1 successful login at 23:47 UTC.",
        "Alert: User jsmith downloaded malware_payload.exe from email (hash: d41d8cd98f00b204e9800998ecf8427e). Execution detected.",
        "Alert: Connection to 192.0.2.10:22 from external IP. SSH key-based authentication failed. 3 attempts.",
    ]
    
    print("\n" + "="*80)
    print("AI SOC ASSISTANT - WORKING PROTOTYPE (Day 28)")
    print("="*80)
    
    results = []
    for i, alert in enumerate(sample_alerts, 1):
        print(f"\n{'─'*80}")
        print(f"ALERT {i}")
        print(f"{'─'*80}")
        
        result = assistant.triage_alert(alert)
        report = assistant.format_report(result)
        results.append(report)
        print(report)
    
    # Save combined report
    combined_report = "\n\n".join(results)
    with open("day28_prototype_output.md", "w") as f:
        f.write("# AI SOC Assistant - Day 28 Prototype Output\n\n")
        f.write(combined_report)
    
    print("\n" + "="*80)
    print(f"Triage complete. Output saved to: day28_prototype_output.md")
    print("="*80)


if __name__ == "__main__":
    main()
